apiVersion: v1
kind: Service
metadata:
  name: api-dev
  namespace: api
  labels: 
    app: api-dev
spec:
  type: NodePort
  selector:
    app: api-dev
  ports: 
    - port: 80
      targetPort: 80
      nodePort: 30080                       #Added nodePort value
